apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegisai
resources:
  - ../../../base/application
images:
  - name: aegisai-backend
    newName: ghcr.io/debrc/aegisai-backend
    newTag: replace-with-immutable-image-tag
  - name: aegisai-frontend
    newName: ghcr.io/debrc/aegisai-frontend
    newTag: replace-with-immutable-image-tag
